linters-settings:
  misspell:
    locale: US

  gofumpt:
    extra-rules: false

  revive:
    rules:
      - name: unused-parameter
        disabled: true

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - revive
    - ineffassign
    - prealloc
    - unconvert
    - gofumpt

issues:
  exclude-use-default: false
